env: "local"
storage_path: "./storage/storage.db"
http_server:
  address: ":8080"
  timeout: 5s
  idle_timout: 30s
minio:
  minio_access_key_id: 123123123
  minio_secret_access_key: 123123123
  minio_bucket_name: "bucket"
  minio_endpoint: "localhost:9000"