version: '3'

env:
  # ENV CONFIG FOR APPLICATION
  CONFIG_PATH: /home/user/GolandProjects/pastebin-v0.0.1/app/config/local.yaml

  # MINIO
  MINIO_ROOT_USER: dev
  MINIO_ROOT_PASSWORD: devdev123
  MINIO_USE_SSL: false
  MINIO_BUCKET_NAME: bucket
  MINIO_ACCESS_KEY: 123123123
  MINIO_SECRET_KEY: 123123123

tasks:
  run:
    desc: "Run application with environment variables"
    cmd:
      go run cmd/pastebin/main.go

  build:
    desc: "build app and  minio docker with env variables"
    cmds:
      - docker compose -f ../docker-compose.app.yaml up --build
      - docker compose -f ../docker-compose.minio.yaml up --build -d

  up:
    desc: "run app and minio docker with env variables"
    cmds:
        - docker compose -f ../docker-compose.minio.yaml up -d
        - docker compose -f ../docker-compose.app.yaml up
        -

  down:
    desc: "down app and minio docker with env variables"
    cmds:
      - docker compose -f ../docker-compose.app.yaml down
      - docker compose -f ../docker-compose.minio.yaml down

  #Only Minio
  build-minio:
    desc: "build only minio"
    cmd:
      docker compose -f ../docker-compose.minio.yaml up --build -d

  up-minio:
    desc: "up only minio"
    cmd:
      docker compose -f ../docker-compose.minio.yaml up -d

  down-minio:
    desc: "down only minio"
    cmd:
      docker compose -f ../docker-compose.minio.yaml down
