version: '3'

env:
  # ENV CONFIG FOR APPLICATION
  CONFIG_PATH: /home/user/GolandProjects/pastebin-v0.0.1/app/config/local.yaml

  # MINIO
  MINIO_ROOT_USER: dev
  MINIO_ROOT_PASSWORD: devdev123
  MINIO_USE_SSL: false
  MINIO_BUCKET_NAME: bucket

tasks:
  run:
    desc: "Run application with environment variables"
    cmd:
      go run cmd/pastebin/main.go
  build:
    dir: '{{.USER_WORKING_DIR}}'
    desc: "build minio docker with env variables"
    cmd:
      ../docker compose up --build
  up:
    dir: '{{.USER_WORKING_DIR}}'
    desc: "run minio docker with env variables"
    cmd:
      docker compose up
  down:
    dir: '{{.USER_WORKING_DIR}}'
    desc: "run minio docker with env variables"
    cmd:
      docker compose down